CalculatorZd/CalculatorZd/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BO;
using BO.Implementation.Caching;
using CalculatorZd.Models;
using CalculatorZd.Services;
using Common.Api;
using DA.Filters;

namespace CalculatorZd.Controllers
{
    public class CalculatorController : Controller
    {
        private const int LengthListShow = 20;

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
               // var model = new CalculatorViewModel();
                  //  model.FilterList = GetCalcFilterList();
                    return View();
            }
            
            return RedirectToAction("Login", "Account");
        }

        public JsonResult GetWagonTypes()
        {
            List<FilterWagonTypeViewModel> model = FilterService.GetWagonTypes();
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCountriesSending(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.CountriesSendingFilterName, LengthListShow,
                FilterNameHelper.CountriesSendingFilterName);
        }

        public JsonResult GetFirms(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.CompanySendingEGRPOFilterName, 15);
        }

        public JsonResult GetTransportationType()
        {
            return GetFilterListAll(FilterNameHelper.TransportationTypeFilterName, Constants.SELECT_VALUES);
        }

        public JsonResult GetOwnerVagon(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.OwnerVagonEGRPOFilterName, 15);
        }

        public JsonResult GetRenterVagon(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.RenterVagonGVCFilterName, 15);
        }

        public JsonResult GetPayer(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.PayerFilterName, 15);
        }

        public JsonResult GetCompanySending(string term)
        {
            return GetCompanySendingListByTerm(1, term, FilterNameHelper.CompanySendingFilterName, 15);
        }


        public JsonResult GetCompanyRecipient(string term)
        {
            return GetCompanySendingListByTerm(1, term, FilterNameHelper.CompanyRecipientFilterName, 15);
        }

        public JsonResult GetContainerVolume()
        {
            return GetFilterListAll(FilterNameHelper.ContainerVolumeFilterName, Constants.SELECT_VALUES);
        }

        public JsonResult GetSubjectsSending(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.SubjectsSendingFilterName, 15);
        }


        public JsonResult GetCargoNames(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.CargoNameFilterName, 15);
        }

        public CalculatorFiltersSearchResult GetCalcFilterList()
        {
            if (SessionManager.FirmInfo == null)
                return null;

            var model = new CalculatorFiltersSearchResult();
            var filterItems = new List<CalcFilterItem>();
            Guid firmid = SessionManager.FirmInfo.ID;
            List<CalcFirmSettings> dbfl = FiltersAdapter.GetCalculatorFirmFilterList(firmid);
            foreach (CalcFirmSettings filterItem in dbfl)
            {
                filterItems.Add(new CalcFilterItem {FilterID = filterItem.ID, FilterName = filterItem.FilterName});
            }
            model.FilterItems = filterItems;
            return model;
        }


        //public JsonResult GetCargoClassName(string term)
        //{
        //    return GetFilterListAll(CombineColumns(ColumnsMapping.CargoCode.GetStringValue(), ColumnsMapping.CargoClassName.GetStringValue()));
        //}
        public JsonResult GetCargoGroupNames()
        {
            return GetFilterListAll(FilterNameHelper.CargoGroupNamesFilterName, Constants.SELECT_VALUES);
        }

        public JsonResult GetWaysSending(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.WaySendingFilterName, LengthListShow,
                FilterNameHelper.WaySendingFilterName);
        }

        public JsonResult GetWaysDelivering(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.WayDeliveringFilterName, LengthListShow,
                FilterNameHelper.WaySendingFilterName);
        }

        public JsonResult GetStationsSending(string term)
        {
            return GetFilterListByFilterArray(1, term, FilterNameHelper.StationsSendingFilterNameArr, "", "", "",
                FilterNameHelper.StationsSendingFilterKey);
        }

        public JsonResult GetCountriesDelivering(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.CountriesDeliveringFilterName, LengthListShow,
                FilterNameHelper.CountriesDeliveringFilterName);
        }

        public JsonResult GetSubjectsDelivering(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.SubjectsDeliveringFilterName, LengthListShow,
                FilterNameHelper.SubjectsDeliveringFilterName);
        }


        public JsonResult GetCargoNameEarlyTransportation(string term)
        {
            return GetFilterListByTerm(1, term, FilterNameHelper.CargoNameEarlyTransportationFilterName, LengthListShow,
                FilterNameHelper.CargoNameEarlyTransportationFilterName);
        }

        public JsonResult GetStationsDelivering(string term, string filter)
        {
            return GetFilterListByFilterArray(1, term, FilterNameHelper.StationsDeliveringFilterNameArr, "", "", "",
                FilterNameHelper.StationsDeliveringFilterKey);
        }

        private JsonResult GetFilterListByFilterArray(int minLength, string term, string[] filterName, string sWhere,
            string orderBy, string defaultValue = "", string cacheKey = "")
        {
            IEnumerable<string> list = FilterService.GetFilterListByTerm(minLength, term, filterName[0], filterName[1],
                20, defaultValue, cacheKey);
            if (list != null && list.Any())
            {
                if (!String.IsNullOrEmpty(orderBy))
                {
                    list.OrderBy(s => s);
                }
                return Json(list, JsonRequestBehavior.AllowGet);
                ;
            }
            return Json(new object(), JsonRequestBehavior.AllowGet);
        }

        private JsonResult GetFilterListByTerm(int termLength, string term, string filterName, int lengthListShow,
            string ordeBy = "")
        {
            IEnumerable<string> list = FilterService.GetFilterListByTerm(termLength, term, filterName, lengthListShow);

            if (list != null && list.Any())
            {
                if (!String.IsNullOrEmpty(ordeBy))
                {
                    list.OrderBy(s => s);
                }
                return Json(list, JsonRequestBehavior.AllowGet);
            }
            return Json(new object(), JsonRequestBehavior.AllowGet);
        }

        private JsonResult GetCompanySendingListByTerm(int termLength, string term, string filterName,
            int lengthListShow, string ordeBy = "")
        {
            IEnumerable<string> list = FilterService.GetFilterListByTerm(termLength, term, filterName, lengthListShow);

            list = GetFormatedList(list);

            if (list != null && list.Any())
            {
                if (!String.IsNullOrEmpty(ordeBy))
                {
                    list.OrderBy(s => s);
                }
                return Json(list, JsonRequestBehavior.AllowGet);
            }
            return Json(new object(), JsonRequestBehavior.AllowGet);
        }

        private IEnumerable<string> GetFormatedList(IEnumerable<string> list)
        {
            var retList = new List<string>();
            foreach (string item in list)
            {
                string[] arr = item.Split('|');
                string code = arr[0];
                retList.Add(String.Format("{0} | {1}", code.Substring(code.Length - 9, 9), arr[1]));
            }
            return retList;
        }

        private JsonResult GetFilterListAll(string filterName, string defaultValue = "", string orderBy = "")
        {
            IEnumerable<FilterTypeViewModel> types = FilterService.GetFilterListAll(filterName, defaultValue, orderBy);
            return Json(types, JsonRequestBehavior.AllowGet);
        }
    }
}

CalculatorZd/CalculatorZd/Controllers/FirmReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CalculatorZd.Models;
using CalculatorZd.Services;
using Common.Api;

namespace CalculatorZd.Controllers
{
    public class FirmReportController : Controller
    {
        //
        // GET: /FirmReport/

         ReportService _service = new ReportService();
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var model = new FirmReportViewModel {FirmReports = _service.GetReportByFirm(SessionManager.FirmInfo.ID)};
                return View("Index", model);
            }
            else
            {
              return RedirectToAction("Login", "Account");
            }
        }
	}
}

CalculatorZd/CalculatorZd/Views/Shared/_Layout.cshtml
@using Common.Api
@using Localization.WebResources.WebResources
@{
    bool isNonActivated = User.Identity.IsAuthenticated && SessionManager.FirmInfo!=null && SessionManager.FirmInfo.IsNonActivated;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title  Калькулятор жд перевозок</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    @*<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="nav-collapse collapse" style="display: inline;">
                    <ul class="nav">
                        <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                        <li>@Html.ActionLink("Калькулятор", "Index", "Calculator")</li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Отчеты", "index", "FirmReport")</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        @if (isNonActivated)
        {
            <p style="color:red;">@AccountResource.EmailActivationLink</p>
        }
    
        @RenderBody()
      
    </div>
   
    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
  

    @RenderSection("scripts", required: false)
</body>
</html>

CalculatorZd/CalculatorZd/Views/Shared/_NgLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Калькулятор</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*@Scripts.Render("~/bundles/ngBase")*@
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jquery-ui")
    @*<link href="~/Content/bootstrap/bootstrap.css" rel="stylesheet" />*@
    @*@Scripts.Render("~/bundles/bootstrap/js")*@

    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">

    @*@Styles.Render("~/bundles/bootstrap-select/css")*@

    @*<link href="~/Content/bootstrap/bootstrap-select.min.css" rel="stylesheet" />*@

    @*<script src="~/Scripts/jquery-2.0.3.min.js"></script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jquery-ui")
    <script src="~/Scripts/jquery.blockUI.js"></script>
    @*<script src="~/Scripts/bootstrap-select.js"></script>*@
    @Scripts.Render("~/bundles/ngBase")
    @*<script src="~/Scripts/angular-bootstrap-select.min.js"></script>*@

    @*<script src="~/Scripts/selectDemo/marked.js"></script>*@
    @*<script src="~/app/ng/controllers/select.js"></script>
    <script src="~/app/ng/services/dataService.js"></script>*@
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jquery-jgrowl/1.2.12/jquery.jgrowl.min.css" />
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="nav-collapse collapse" style="display: inline;">
                    <ul class="nav">
                        <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                        <li>@Html.ActionLink("Калькулятор", "Index", "Calculator")</li>
                         
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Отчеты", "index", "FirmReport")</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div ng-app="app">
        @RenderBody()
    </div>
</body>
</html>