CalculatorZd/CalculatorZd/Controllers/ForgotPasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BO;
using BO.Implementation;
using CalculatorZd.Models;
using Common.Api;
using DA;
using Microsoft.AspNet.Identity;
using Utils;

namespace CalculatorZd.Controllers
{
    public class ForgotPasswordController : Controller
    {
          public ForgotPasswordController() : this(IdentityConfig.Secrets, IdentityConfig.Logins, IdentityConfig.Users, IdentityConfig.Roles) { }

          public ForgotPasswordController(IUserSecretStore secrets, IUserLoginStore logins, IUserStore users, IRoleStore roles)
        {
            Secrets = secrets;
            Logins = logins;
            Users = users;
            Roles = roles;
        }

        public IUserSecretStore Secrets { get; private set; }
        public IUserLoginStore Logins { get; private set; }
        public IUserStore Users { get; private set; }
        public IRoleStore Roles { get; private set; }
        public ActionResult Index(string activationCode)
        {
            Guid code = Guid.Empty;

            if (!String.IsNullOrEmpty(activationCode) && Guid.TryParse(activationCode, out code) && code != Guid.Empty)
            {
                Firm firm = FirmAdapter.GetFirmIDByActivationCode(code, (int) ActivationType.ActivationChangePassword);

                if (firm!=null && firm.ID != Guid.Empty)
                {
                    var modelChPass = new ChangeUserPasswordViewModel();
                    modelChPass.UserName = firm.Login;
                    return View("ChangePassword", modelChPass);
                }
                else
                {
                    return View("ActivationCodeFailure");
                }
            }

            var model = new ForgetPasswordViewModel();
            return View("Index", model);
        }

        public ActionResult TryRestorePassword(ForgetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                Firm firmRestored = FirmsManager.GetLoginByEmail(model.Email);
                if (firmRestored != null)
                {
                    Guid activationCode = Guid.NewGuid();
                    if (FirmAdapter.CreateRestorePasswordActivationInfo(firmRestored.ID, activationCode, (int)ActivationType.ActivationChangePassword))
                    {
                        if (!MailService.SendRestorePasswordLink(activationCode.ToString(), firmRestored.AdminEmail))
                        {
                            model.StatusMailSending = MailSendingStatus.Failure;
                            return View("Index", model);
                        }
                    }
                    ViewBag.EmailForRestorePassword = model.Email;
                    ViewBag.MailProviderName = model.Email.Split('@')[1];
                }
                else
                {
                    var fpModel = new ForgetPasswordViewModel();
                    fpModel.EmailNotFound = true;
                    return View("Index", fpModel);
                }
                return View();
            }
            else
            {
                return View("Index", new ForgetPasswordViewModel());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangeUserPasswordViewModel model)
        {
            Guid actCode = Guid.Empty;
            if (ModelState.IsValid && Guid.TryParse(model.ActivationCode, out actCode))
            {
                bool changePasswordSucceeded = false;
                changePasswordSucceeded = await ChangePassword(model.UserName, model.NewPassword);
             
                if (changePasswordSucceeded)
                {
                    FirmAdapter.ActivateActivationCode(actCode, (int)ActivationType.ActivationChangePassword);
                    return RedirectToAction("PasswordChangedSuccess");
                }
                else
                {
                    ModelState.AddModelError(String.Empty, "The current password is incorrect or the new password is invalid.");
                }
            }
            return View();
        }

        public ActionResult PasswordChangedSuccess()
        {
            return View();
        }

        private async Task<bool> ChangePassword(string userName, string newPassword)
        {
            bool changePasswordSucceeded = await Secrets.UpdateSecret(userName, newPassword);
            return changePasswordSucceeded;
        }
    }
}

CalculatorZd/CalculatorZd/Views/ForgotPassword/ActivationCodeFailure.cshtml
@{
    ViewBag.Title = "Сменна пароля";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<br />
<div style="width:100%;text-align:center;">
    <div style="color:red; font-size:16px">Код смены пароля неверен или истек <span style="color:green"><a href="/ForgotPassword">отправить новый код смены пароля</a></span></div>
</div>

CalculatorZd/CalculatorZd/Views/ForgotPassword/ChangePassword.cshtml
@model CalculatorZd.Models.ChangeUserPasswordViewModel
@{
    ViewBag.Title = ">Смена пароля";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Смена пароля</h2>
@using (Html.BeginForm("ChangePassword", "ForgotPassword"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary()

    <fieldset class="form-horizontal">
        <legend>Смена пароля</legend>
        <div class="control-group">
            @Html.LabelFor(m => m.NewPassword, new { @class = "control-label" })
            <div class="controls">
                @Html.PasswordFor(m => m.NewPassword)
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "control-label" })
            <div class="controls">
                @Html.PasswordFor(m => m.ConfirmPassword)
            </div>
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Сменить пароля" class="btn" />
        </div>
    </fieldset>
    @Html.HiddenFor(m => m.UserName)
    @Html.HiddenFor(m => m.ActivationCode)
}

CalculatorZd/CalculatorZd/Views/ForgotPassword/Index.cshtml
@using System.Web.UI.WebControls
@using BO.Implementation
@using CalculatorZd.Models
@model CalculatorZd.Models.ForgetPasswordViewModel
@{
    ViewBag.Title = "Забыли пароль?";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hgroup class="title">
    <h3>Забыли пароль?</h3>
</hgroup> 
<div class="row-fluid">
    <div class="span6">
        <section id="loginForm">
            @using (Html.BeginForm("TryRestorePassword", "ForgotPassword"))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <fieldset class="form-horizontal">
                    <legend> </legend>
                    <div class="control-group">
                        <div style="font-size:14px">В форму ниже введите свой электронный адрес, указанный при регистрации, и через несколько минут на Ваш E-mail придет письмо с ссылкой для восстановления пароля</div>
                        <br />
                        @Html.LabelFor(m => m.Email, new { @class = "control-label" })
                        <div class="controls">
                            @Html.TextBoxFor(m => m.Email)
                            @Html.ValidationMessageFor(m => m.Email, null, new { @class = "help-inline" })

                        </div>
                        @if (Model.EmailNotFound)
                        {
                            <div class="controls">
                                <span style="color: red;">Указанный email не найден или не активирован на сайте</span>
                            </div>
                        }
                        <div class="controls">
                            <br />
                            <input type="submit" value="Отправить" class="btn" />
                        </div>
                    </div>

                    @if (Model.StatusMailSending == MailSendingStatus.Failure)
                    {
                        <div class="controls">
                            <span style="color: red;">Во врем отправки письма с ссылкой для смены пароля произошла ошибка! Попробуйте позднее или обратитесь в службу технической поддержки.</span>
                        </div>
                    }
                </fieldset>
            }
        </section>
    </div>

</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CalculatorZd/CalculatorZd/Views/ForgotPassword/PasswordChangedSuccess.cshtml
@{
    ViewBag.Title = "Смена пароля";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br/>
<br />
<br />
<div style="width:100%;text-align:center;">
    <div style="color:green; font-size:16px">Вы успешно сменили пароль! <a href="/Account/Login">вход</a></div>
</div>

CalculatorZd/CalculatorZd/Views/ForgotPassword/TryRestorePassword.cshtml
@{
    ViewBag.Title = "Забыли пароль?";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Забыли пароль?</h2>
<div style="font-size:14px">
    На e-mail <b>@ViewBag.EmailForRestorePassword</b>  выслано письмо с ссылкой для смены пароля. Проверить почту на <a href='@String.Format("http://{0}",ViewBag.MailProviderName)'>@ViewBag.MailProviderName</a>
</div>